### ISSUE TITLE
Compiler timed out or encountered an error

### ISSUE THREAD

**Issue by rickkas7** [spark/particle-dev#213] opened 2017-06-29 19:02 UTC
A simple code syntax error can cause a "compiler timed out or encountered an error" in the bottom status bar and if you click on that the top display shows "There were no compile errors."

This can be reproduced only if:

- You have a .ino source file
- You have a project.properties file
- You are targeting system firmware 0.6.0 or later
- You have a syntax error

I used this source for the test:

```
void setup() {

}

void loop() {
    int junk
}
```

The int junk is obviously missing a semi-colon at the end of the line.

![incorrect_error](https://user-images.githubusercontent.com/1074604/27705143-076935c0-5cdb-11e7-8ad0-0fcc38ead1db.png)

If I remove the project.properties file I get the correct error message:

![correct_error](https://user-images.githubusercontent.com/1074604/27705190-29653728-5cdb-11e7-9c2c-e10bd5e9316a.png)

I can also put the project.properties back file and rename the file testdev.cpp and I get the correct error message. The project.properties file was empty.

The src directory doesn't make a difference; it works the same way if all of the source is in a single directory.

I was building for a Photon and 0.6.2 when I ran this test. It seems to happen for 0.6.0 and later for both Photon and Electron. Switching to 0.5.3 shows the correct error even if you have both a project.properties and a .ino source file.

**Comment by suda** [comment] 2017-06-30 11:30
Thanks for the detailed report! This seems to be a duplicate of #211

**Closed by suda** 2017-06-30 11:30 UTC
Labels: duplicate
